const C="entregas",CFG="configuracoes/entregador";let db,auth,unsub,data=[],page="home",cfg={valorEntregaCentavos:0};
const $=s=>document.querySelector(s),money=c=>(Number(c||0)/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"America/Sao_Paulo"});
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c])),v=(o,k,d="")=>o&&o[k]!==undefined&&o[k]!==null?o[k]:d;
function setStatus(t,ok=false){$("#firebaseStatus").innerHTML=`<span class="dot ${ok?"ok":"warn"}">●</span> ${t}`;}
function configured(){const c=window.FIREBASE_CONFIG||{};return c.apiKey&&c.authDomain&&c.projectId&&c.appId;}
function shell(title,html){$("#pageTitle").textContent=title;$("#content").innerHTML=html;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));}
function loc(e){return v(e,"semEndereco",false)?v(e,"enderecoReferencia","Sem endereço"):[v(e,"predio"),v(e,"bloco"),v(e,"apartamento")].filter(Boolean).join(" • ")||"Endereço não informado";}
function date(s){return s?new Date(s+"T12:00:00").toLocaleDateString("pt-BR"):"—";}
function parseMoney(s){const n=Number(String(s||"").replace(/R\$\s?/,"").replace(/\./g,"").replace(",","."));return Number.isFinite(n)&&n>=0?Math.round(n*100):null;}
function warn(){return configured()?"":'<div class="notice warning"><b>Firebase aguardando configuração.</b><br>Cadastre o app Web no projeto e preencha <code>dashboard/firebase-config.js</code>.</div>';}
function login(){shell("Acesso ao painel",'<div class="login-wrap"><article class="panel login-card"><div class="setting-icon">SF</div><small>PAINEL DO RESPONSÁVEL</small><h2>Entrar no Sistema de Entregas</h2><p>Use a conta criada em Firebase Authentication.</p><label class="field"><span>E-mail</span><input id="email" type="email"></label><label class="field"><span>Senha</span><input id="password" type="password"></label><button class="primary" id="login">ENTRAR</button><div id="loginMsg" class="save-msg"></div></article></div>');$("#login").onclick=async()=>{try{await auth.signInWithEmailAndPassword($("#email").value.trim(),$("#password").value); }catch(e){$("#loginMsg").textContent="Não foi possível entrar: "+e.message;$("#loginMsg").className="save-msg error";}};}
async function loadCfg(){const s=await db.doc(CFG).get();cfg=s.exists?{...cfg,...s.data()}:{...cfg};}
function subscribe(){if(unsub)unsub();unsub=db.collection(C).onSnapshot(s=>{data=s.docs.map(d=>({id:d.id,...d.data()}));data.sort((a,b)=>String(v(b,"criadoEm")).localeCompare(String(v(a,"criadoEm"))));render();},e=>error(e));}
function row(e){const done=v(e,"realizada",false);return `<button class="delivery-row" data-id="${esc(e.id)}"><span class="delivery-main"><b>${esc(loc(e))}</b><small>${date(v(e,"dia"))} · ${done?"Realizada":"Pendente"}</small></span><span class="badge ${done?"success":"pending"}">${done?"Realizada":"Pendente"}</span></button>`;}
function bind(){document.querySelectorAll(".delivery-row").forEach(b=>b.onclick=()=>detail(b.dataset.id));}
function home(){const t=today(),list=data.filter(e=>v(e,"dia")===t),done=list.filter(e=>v(e,"realizada",false)),pending=list.length-done.length,tips=done.reduce((s,e)=>s+Number(v(e,"caixinhaCentavos",0)),0),pay=Number(v(cfg,"valorEntregaCentavos",0));shell("Visão geral",warn()+`<div class="hero"><div><small>HOJE</small><h2>Controle das entregas</h2><p>Acompanhe o que foi registrado pelo entregador no APK.</p></div><strong class="hero-icon">▣</strong></div><div class="stats"><article><small>ENTREGAS HOJE</small><strong>${list.length}</strong><span>Registradas</span></article><article><small>PENDENTES</small><strong>${pending}</strong><span>Aguardando conclusão</span></article><article><small>REALIZADAS</small><strong>${done.length}</strong><span>Concluídas hoje</span></article><article><small>CAIXINHA</small><strong>${money(tips)}</strong><span>Hoje</span></article></div><div class="columns"><article class="panel"><small>ACOMPANHAMENTO</small><h3>Entregas recentes</h3><div class="delivery-list">${list.slice(0,8).map(row).join("")||'<div class="empty"><strong>Nenhuma entrega sincronizada</strong><p>Quando o entregador registrar uma entrega no APK, ela aparecerá aqui.</p></div>'}</div></article><article class="panel"><small>ENTREGADOR</small><h3>Resumo do dia</h3><div class="rows"><div>Valor por entrega <b>${money(pay)}</b></div><div>Entregas realizadas <b>${done.length}</b></div><div>Total a pagar <b>${money(pay*done.length)}</b></div></div></article></div>`);bind();}
function deliveries(filter=null){let list=data.filter(e=>filter===null||Boolean(v(e,"realizada",false))===filter);shell(filter===false?"Pendentes":filter===true?"Realizadas":"Entregas",`<div class="page-head"><div><small>ENTREGAS</small><h2>${filter===false?"Pendentes":filter===true?"Realizadas":"Todas as entregas"}</h2><p>${list.length} registro(s).</p></div></div><div class="toolbar"><input id="search" placeholder="Buscar por prédio, bloco, apartamento ou referência"><select id="day"><option value="">Todos os dias</option>${[...new Set(list.map(e=>v(e,"dia")).filter(Boolean))].sort().reverse().map(d=>`<option value="${d}">${date(d)}</option>`).join("")}</select></div><div id="list" class="delivery-list large-list">${list.map(row).join("")||'<div class="panel empty"><strong>Nenhuma entrega encontrada.</strong></div>'}</div>`);const apply=()=>{const q=$("#search").value.toLowerCase(),d=$("#day").value;const x=list.filter(e=>(!q||(`${loc(e)} ${v(e,"observacao")}`).toLowerCase().includes(q))&&(!d||v(e,"dia")===d));$("#list").innerHTML=x.map(row).join("")||'<div class="panel empty"><strong>Nenhuma entrega encontrada.</strong></div>';bind();};$("#search").oninput=apply;$("#day").onchange=apply;bind();}
function detail(id){const e=data.find(x=>x.id===id);if(!e)return;shell("Detalhes da entrega",`<div class="page-head"><div><small>DETALHES</small><h2>${esc(loc(e))}</h2><p>${date(v(e,"dia"))}</p></div><button class="secondary" id="back">VOLTAR</button></div><div class="detail-grid"><article class="panel"><small>LOCAL</small><div class="detail-value">${esc(loc(e))}</div><div class="detail-meta">Prédio: ${esc(v(e,"predio","—"))} · Bloco: ${esc(v(e,"bloco","—"))} · Apto: ${esc(v(e,"apartamento","—"))}</div></article><article class="panel"><small>PAGAMENTO INICIAL</small><div class="detail-value">${esc(v(e,"pagamentoInicial","Não informado"))}</div><div class="detail-meta">Valor da compra: ${money(v(e,"valorCompraCentavos",0))}</div></article><article class="panel"><small>RESULTADO</small><div class="detail-value">${v(e,"realizada",false)?esc(v(e,"resultadoPagamento","")):"Pendente"}</div><div class="detail-meta">Forma: ${esc(v(e,"formaPagamento","—")||"—")}</div></article><article class="panel"><small>CAIXINHA</small><div class="detail-value">${money(v(e,"caixinhaCentavos",0))}</div><div class="detail-meta">Observação: ${esc(v(e,"observacao","—")||"—")}</div></article></div>`);$("#back").onclick=()=>deliveries(null);}
function finance(){const t=today(),done=data.filter(e=>v(e,"dia")===t&&v(e,"realizada",false)),per=Number(v(cfg,"valorEntregaCentavos",0)),tips=done.reduce((s,e)=>s+Number(v(e,"caixinhaCentavos",0)),0);shell("Financeiro",`<div class="page-head"><div><small>FINANCEIRO</small><h2>Resumo de hoje</h2><p>${done.length} entrega(s) realizada(s).</p></div></div><div class="stats"><article><small>REALIZADAS</small><strong>${done.length}</strong><span>Hoje</span></article><article><small>VALOR POR ENTREGA</small><strong>${money(per)}</strong><span>Configurado</span></article><article><small>TOTAL A PAGAR</small><strong>${money(per*done.length)}</strong><span>Hoje</span></article><article><small>CAIXINHAS</small><strong>${money(tips)}</strong><span>Hoje</span></article></div><article class="panel"><small>REGRA</small><h3>Cálculo</h3><p class="muted-text">Total a pagar = valor por entrega × quantidade de entregas realizadas. A caixinha é mostrada separadamente.</p></article>`);}
async function settings(){await loadCfg();shell("Configurações",warn()+`<div class="settings-grid"><article class="panel settings-card"><div class="setting-icon">R$</div><div><small>VALOR POR ENTREGA</small><h3>Pagamento do entregador</h3><p>Este valor é usado no cálculo financeiro e não altera a compra do cliente.</p></div><label class="field"><span>Valor por entrega</span><input id="valor" inputmode="decimal" placeholder="0,00" value="${cfg.valorEntregaCentavos?(cfg.valorEntregaCentavos/100).toLocaleString("pt-BR",{minimumFractionDigits:2}):""}"></label><button class="primary" id="save">SALVAR CONFIGURAÇÃO</button><div id="msg" class="save-msg"></div></article><article class="panel info-card"><small>COMO FUNCIONA</small><h3>Regra do sistema</h3><div class="rule"><span>1</span><p>O entregador registra a entrega no APK.</p></div><div class="rule"><span>2</span><p>O Dashboard contabiliza as realizadas.</p></div><div class="rule"><span>3</span><p>O valor configurado é multiplicado pelas realizadas.</p></div><div class="preview"><small>VALOR ATUAL</small><strong>${money(cfg.valorEntregaCentavos)}</strong></div></article></div>`);$("#save").onclick=async()=>{const n=parseMoney($("#valor").value);if(n===null){$("#msg").textContent="Informe um valor válido.";$("#msg").className="save-msg error";return;}try{await db.doc(CFG).set({valorEntregaCentavos:n,atualizadoEm:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});cfg.valorEntregaCentavos=n;$("#msg").textContent="Configuração salva no Firebase." ;$("#msg").className="save-msg ok";}catch(e){$("#msg").textContent=e.message;$("#msg").className="save-msg error";}};}
function error(e){shell("Erro",`<div class="notice error"><b>Erro no Firebase.</b><p>${esc(e.message||e)}</p></div>`);}
function render(){if(!configured()){setStatus("Firebase aguardando configuração");home();return;}if(!auth.currentUser){setStatus("Faça login");login();return;}setStatus("Firebase conectado",true);if(page==="home")home();else if(page==="deliveries")deliveries(null);else if(page==="pending")deliveries(false);else if(page==="completed")deliveries(true);else if(page==="finance")finance();else settings();}
document.querySelectorAll("nav button[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;render();});$("#logoutButton").onclick=()=>auth&&auth.signOut();
if(configured()){firebase.initializeApp(window.FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(async u=>{if(u){await loadCfg();subscribe();}render();});}else render();